Lesson8 try1
sneoxx/Java-Courses-Zaraev pull request #11
Opened 2021-04-17 09:48 UTC by sneoxx

2021-04-17 15:04 UTC, tlt-java-courses requested changes
Замечания:
- Форматирование кода
  - Отступы и форматирование кода и файлов 
  - Некорректные пути пакетов
- Проблемы в коде
  - Классы с Generics типами, инициализируются с Raw типами
  - Публичные переменные в коде, без явной на то необходимости
  - Бесполезные конструкторы в Exceptions
- Логгирование 
  - Использование System.out.println, а не логгера
- JavaDoc
  - Отсутвие JavaDoc на классах
  - Часть JavaDoc в коде не информативное
  - Длина строки документации рекомендованных > 120 символов

Рекомендации:
- Разносить информацию в логах на INFO и DEBUG уровни. Я включил INFO логи и не увидел никакой полезной информации. Один мусор.
- Рассортировать классы на подпакеты, например Exceptions в пакет exceptions

2021-04-18 10:31 UTC, sneoxx commented
> 
> 
> Замечания:
> 
>     * Форматирование кода
>       
>       * Отступы и форматирование кода и файлов
>       * Некорректные пути пакетов
> 
>     * Проблемы в коде
>       
>       * Классы с Generics типами, инициализируются с Raw типами
>       * Публичные переменные в коде, без явной на то необходимости
>       * Бесполезные конструкторы в Exceptions
> 
>     * Логгирование
>       
>       * Использование System.out.println, а не логгера
> 
>     * JavaDoc
>       
>       * Отсутвие JavaDoc на классах
>       * Часть JavaDoc в коде не информативное
>       * Длина строки документации рекомендованных > 120 символов
> 
> 
> Рекомендации:
> 
>     * Разносить информацию в логах на INFO и DEBUG уровни. Я включил INFO логи и не увидел никакой полезной информации. Один мусор.
> 
>     * Рассортировать классы на подпакеты, например Exceptions в пакет exceptions

1

2021-04-18 10:48 UTC, sneoxx commented
> 
> 
> Замечания:
> 
>     * Форматирование кода
>       
>       * Отступы и форматирование кода и файлов
>       * Некорректные пути пакетов
> 
>     * Проблемы в коде
>       
>       * Классы с Generics типами, инициализируются с Raw типами
>       * Публичные переменные в коде, без явной на то необходимости
>       * Бесполезные конструкторы в Exceptions
> 
>     * Логгирование
>       
>       * Использование System.out.println, а не логгера
> 
>     * JavaDoc
>       
>       * Отсутвие JavaDoc на классах
>       * Часть JavaDoc в коде не информативное
>       * Длина строки документации рекомендованных > 120 символов
> 
> 
> Рекомендации:
> 
>     * Разносить информацию в логах на INFO и DEBUG уровни. Я включил INFO логи и не увидел никакой полезной информации. Один мусор.
> 
>     * Рассортировать классы на подпакеты, например Exceptions в пакет exceptions



> 
> 
> Замечания:
> 
>     * Форматирование кода
>       
>       * Отступы и форматирование кода и файлов
>       * Некорректные пути пакетов
> 
>     * Проблемы в коде
>       
>       * Классы с Generics типами, инициализируются с Raw типами
>       * Публичные переменные в коде, без явной на то необходимости
>       * Бесполезные конструкторы в Exceptions
> 
>     * Логгирование
>       
>       * Использование System.out.println, а не логгера
> 
>     * JavaDoc
>       
>       * Отсутвие JavaDoc на классах
>       * Часть JavaDoc в коде не информативное
>       * Длина строки документации рекомендованных > 120 символов
> 
> 
> Рекомендации:
> 
>     * Разносить информацию в логах на INFO и DEBUG уровни. Я включил INFO логи и не увидел никакой полезной информации. Один мусор.
> 
>     * Рассортировать классы на подпакеты, например Exceptions в пакет exceptions



> 
> 
> Замечания:
> 
>     * Форматирование кода
>       
>       * Отступы и форматирование кода и файлов
>       * Некорректные пути пакетов
> 
>     * Проблемы в коде
>       
>       * Классы с Generics типами, инициализируются с Raw типами
>       * Публичные переменные в коде, без явной на то необходимости
>       * Бесполезные конструкторы в Exceptions
> 
>     * Логгирование
>       
>       * Использование System.out.println, а не логгера
> 
>     * JavaDoc
>       
>       * Отсутвие JavaDoc на классах
>       * Часть JavaDoc в коде не информативное
>       * Длина строки документации рекомендованных > 120 символов
> 
> 
> Рекомендации:
> 
>     * Разносить информацию в логах на INFO и DEBUG уровни. Я включил INFO логи и не увидел никакой полезной информации. Один мусор.
> 
>     * Рассортировать классы на подпакеты, например Exceptions в пакет exceptions

1

2021-04-18 19:14 UTC, tlt-java-courses approved these changes

2021-04-18 19:14 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Cache.java
> + * cache - массив элементов типа CacheElement
Для классов не обязательно расписывать что в них находится. JavaDoc лучше писать с описанием для чего этот класс нужен и какие цели он преследует.

2021-04-18 19:14 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Storage.java
> +        System.out.print(Arrays.toString(storage));
Использование System.out.print

2021-04-18 19:14 UTC, tlt-java-courses commented
Форматирование файлов ты поправил

2021-04-18 19:15 UTC, merged

2021-04-18 19:20 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Cache.java
> +     * Добавление элемента в конец кэша. Если кеш заполенен, удаляется первый элемент, весь сдвигается влево и элемент добавляется в конец
JavaDoc не должен содержать алгоритм работы.

2021-04-18 19:23 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Cache.java
> +     * Поиск элемента в кэше по полю element типа CacheElement
Что есть CacheElement? Я смотрю в код и там нет этого. Что является дезинформацией.