Lesson10 try1
sneoxx/Java-Courses-Zaraev pull request #17
Opened 2021-04-28 08:03 UTC by sneoxx

2021-04-29 17:40 UTC, tlt-java-courses requested changes

2021-04-29 17:40 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/DataApiService.java
> +            month = "100";
Если у тебя stringCount <= 3 то будет 0123, где 1 - N, а 23 - M

2021-04-29 17:40 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/DataApiService.java
> +        LocalDateTime doomsDay = LocalDateTime.now(timeZoneUTC).plusMonths(Long.parseLong(month)).plusDays(Long.parseLong(day));
По клин коду цепочки вызовов лучше переносить на след строку для читаемости. Т.е. 
```java
LocalDateTime.now(timeZoneUTC)
               .plusMonths(Long.parseLong(month))
               .plusDays(Long.parseLong(day));
```

2021-04-29 17:40 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Main.java
> +        DataApiService dataApiService = new DataApiService();
Ты создаёшь тут сервис. Давай тогда его передавать в качестве аргументов конструктора в StreamService

2021-04-29 17:40 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/StreamService.java
> +    DataApiService dataApiService = new DataApiService();
Переменная как минимум должна быть private. И рекомендуется инициализировать в конструкторе. Ещё переменную можно final сделать

2021-04-29 17:40 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Main.java
> +    static String fileName = "src/main/resources/1.txt";
Это не тот файл, что я прикладывал к ДЗ

2021-04-30 09:56 UTC, sneoxx commented on src/main/java/com/zaraev/epam/DataApiService.java
> +            month = "100";
Недопонял, что значит ведущий ноль, исправил - так верно?

2021-04-30 09:57 UTC, sneoxx commented on src/main/java/com/zaraev/epam/Main.java
> +    static String fileName = "src/main/resources/1.txt";
приложил файл, в майне частично заккоментированы строки, чтобы файл не перезаписался

2021-05-01 17:42 UTC, tlt-java-courses requested changes

2021-05-01 17:42 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/DataApiService.java
> +        int lengthStringCount = stringCount.length();
Не слишком усложненный кусок кода в этом методе? Может есть более красивое решение?

2021-05-01 17:42 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/ForEachService.java
> +        ) {
символ закрывающей ')' не переносят одну

2021-05-01 17:42 UTC, tlt-java-courses commented on src/main/java/com/zaraev/epam/Sausage.java
> +public class Sausage {
Давай воспользуемся lombok

2021-05-02 20:25 UTC, tlt-java-courses approved these changes

2021-05-02 20:25 UTC, tlt-java-courses commented on src/test/java/com/zaraev/epam/DataApiServiceTest.java
> +
У тебя блок констант идёт, переносы между ними не нужы

2021-05-02 20:25 UTC, tlt-java-courses commented on src/test/java/com/zaraev/epam/DataApiServiceTest.java
> +    DataApiService dataApiService = new DataApiService();
private

2021-05-02 20:26 UTC, tlt-java-courses approved these changes

2021-05-02 20:26 UTC, merged