Lesson14 try1
sneoxx/Java-Courses-Zaraev pull request #22
Opened 2021-05-20 17:14 UTC by sneoxx

2021-05-21 18:09 UTC, tlt-java-courses requested changes

2021-05-21 18:09 UTC, tlt-java-courses commented on Java-Zaraev-db/src/main/resources/liquibase/db.changelog-master.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Основные ченж логи называют database_{название проекта}_changelog

2021-05-21 18:09 UTC, tlt-java-courses commented on Java-Zaraev-db/src/main/resources/liquibase/db.changelog-0.1.0.xml
> +<?xml version="1.1" encoding="UTF-8" standalone="no"?>
Давай сложим его в подпапку v1

2021-05-21 18:09 UTC, tlt-java-courses commented on Java-Zaraev-db/src/main/resources/liquibase/db.changelog-0.1.0.xml
> +    <changeSet id="2021-05-21_addtableOrderProduct" author="rustam_zaraev">
Имя и фамилия с заглавной буквы.
id хорошо, но описание пишут через lower_snake_case обычно

2021-05-23 00:50 UTC, tlt-java-courses requested changes

2021-05-23 00:50 UTC, tlt-java-courses commented on Java-Zaraev-db/src/main/resources/liquibase/database.java-courses.changelog.xml
> +    <include file="src/main/resources/liquibase/v1/db.changelog-1.1.0.xml"/>
Не очень говорящее название у ченжлога

2021-05-23 00:50 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/domain/entity/Customer.java
> +@Table(name = "customer", schema = "zaraev")
Для чего это излишнее указание?

2021-05-23 00:50 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/domain/entity/Customer.java
> +    private int customerID;
Обычно Id не пишут заглавными

2021-05-23 00:50 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/domain/entity/Customer.java
> +    @Column(name = "customer_name")
hibernate по умолчанию приводит lowerCamelCase к lower_snake_case, поэтому подобные уточнения излишние

2021-05-23 00:50 UTC, tlt-java-courses commented on pom.xml
> +                        <exclude>**/*.class</exclude>
?

2021-05-23 00:50 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/service/ServiceEntity.java
> +    public void testCustomer() {
Методы персистенц слоя не должны содержать бизнес логику. Только работу с БД. Исходя из названия класса. Это сервисный слой. Следовательно нужно создать ещё 4 класса по работе с каждым типом документа

2021-05-23 00:54 UTC, tlt-java-courses commented
Упала ошибка при исполнении кода
`Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "customer_id" violates not-null constraint
  Detail: Failing row contains (null, kyc, 3566).`

2021-05-23 03:19 UTC, sneoxx commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/domain/entity/Customer.java
> +@Table(name = "customer", schema = "zaraev")
убрал, где смог. В классе Order, если убрать schema приводит к ОШИБКА: ошибка синтаксиса (примерное положение: "Order")

2021-05-23 03:38 UTC, sneoxx commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/domain/entity/Customer.java
> +    @Column(name = "customer_name")
убрал, где не приводит к ошибкам

2021-05-23 04:19 UTC, sneoxx commented on pom.xml
> +                        <exclude>**/*.class</exclude>
Отключил тесты, чтобы можно было смержить. Если успею написать тесты верну

2021-05-23 20:08 UTC, tlt-java-courses approved these changes

2021-05-23 20:08 UTC, merged