Lesson17 try1
sneoxx/Java-Courses-Zaraev pull request #28
Opened 2021-06-08 16:38 UTC by sneoxx

2021-06-11 18:57 UTC, tlt-java-courses requested changes
2. Приложенные к заданию постман запросы не работают. Настроел сам - падает ошибка
`org.postgresql.util.PSQLException: ERROR: null value in column &quot;customer_id&quot; violates not-null constraint
  Detail: Failing row contains (null, sddpoe, 477003886).`
![image](https://user-images.githubusercontent.com/75726498/121735530-4fdc9d80-cb07-11eb-83b4-66bebf2134e8.png)
4. 😐
![image](https://user-images.githubusercontent.com/75726498/121736299-6e8f6400-cb08-11eb-9470-427bd01d7d9c.png)

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-api/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResource.java
> +public interface CustomerResource {
Реквест маппинги?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/config/DataSourceConfig.java
> +    public LocalContainerEntityManagerFactoryBean entityManagerFactory() {
Зачем настройка entityManager если мы используем SpringData?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/config/DataSourceConfig.java
> +    public PlatformTransactionManager transactionManager(LocalContainerEntityManagerFactoryBean entityManagerFactory) {
Зачем настройка transactionManager если мы используем SpringData?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResourceImpl.java
> +    @RequestMapping(value = "/customer/{id}", method = RequestMethod.GET)
Почему маппинги в реализации?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResourceImpl.java
> +    @RequestMapping(value = "/customer/{id}", method = RequestMethod.GET)
Почему не заиспользовать GetMapping?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResourceImpl.java
> +    private CustomerService customerService;
Давай автовайрить через конструктор, а его генерить с помощью ломбок

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/service/CustomerService.java
>      CustomerDTO create(CustomerDTO customerDTO);
Сервисный слой ничего не должен знать о Dto

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/service/impl/CustomerServiceImpl.java
> +        customerRepository.saveAndFlush(customer);
Почему просто не заиспользовать save? Для чего его флешать а потом заново за ним в БД лезть?

2021-06-11 18:57 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/webapp/WEB-INF/web.xml
>      <servlet>
Зачем нам этот файл? Если мы используем spring mvc

2021-06-12 09:20 UTC, tlt-java-courses requested changes
Запросы из постман коллекции всё ещё не работают 
![image](https://user-images.githubusercontent.com/75726498/121771529-e39e8000-cb80-11eb-8d4e-f1876e64430a.png)

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/repository/CustomerRepository.java
> + }
Пробел

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/converter/CustomerDTOFromCustomerConverter.java
> +@Component
Можно и так, но давай лучше зарегистрируем конвертеры в конфигурации `WebMvcConfig ` и заиспользуем `ConversionService`, чтобы постоянно не автовайрить стопки конвертеров

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResourceImpl.java
> +    private final CustomerDTOFromCustomerConverter customerDTOfromCustomerConverter;
Давай использовать конвертацию через ConversionService

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/resource/CustomerResourceImpl.java
> +        return customerDTOfromCustomerConverter.convert(customerService.create(customerFromCustomerDTOConverter.convert(customerDTO)));
Давай соблюдать клин код и не писать всёё в одну строку

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/main/java/com/zaraev/epam/javacourses/service/CustomerService.java
> +     * @return - сustomerDTO конвертированный из Customer записанного в базу
JavaDoc

2021-06-12 09:20 UTC, tlt-java-courses commented on Java-Zaraev-impl/src/test/java/com/zaraev/epam/javacourses/service/impl/CustomerServiceImplTest.java
> +//    CustomerRepository customerRepository;
Получается что этот файл нам не нужен

2021-06-12 09:20 UTC, tlt-java-courses commented on pom.xml
> +                <artifactId>h2</artifactId>
Для чего нам inmemory база данных если мы используем postgresql?

2021-06-12 09:27 UTC, sneoxx commented on pom.xml
> +                <artifactId>h2</artifactId>
планировал под тесты

2021-06-12 09:27 UTC, sneoxx commented on Java-Zaraev-impl/src/test/java/com/zaraev/epam/javacourses/service/impl/CustomerServiceImplTest.java
> +//    CustomerRepository customerRepository;
пробовал тесты

2021-06-12 21:06 UTC, merged